### ISSUE TITLE
java.io.IOException: Permission denied 

### ISSUE THREAD

**Issue by lawmake-praveen** [loic-hamdi/multiple_image_picker#9]
I am encountering an issue specifically with accessing the camera on Android 10 in my Flutter application. While the gallery image picking works flawlessly, pressing the camera option triggers the following error. It's noteworthy that this problem is not observed on Android 6 and 12, where the camera functionality operates as expected.

W/System.err(23374): java.io.IOException: Permission denied
W/System.err(23374):    at java.io.UnixFileSystem.createFileExclusively0(Native Method)
W/System.err(23374):    at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
W/System.err(23374):    at java.io.File.createTempFile(File.java:2018)
W/System.err(23374):    at com.sangcomz.fishbun.util.CameraUtil.createImageFile(CameraUtil.java:64)
W/System.err(23374):    at com.sangcomz.fishbun.util.CameraUtil.takePicture(CameraUtil.java:31)
W/System.err(23374):    at com.sangcomz.fishbun.ui.picker.PickerController.takePicture(PickerController.java:41)
W/System.err(23374):    at com.sangcomz.fishbun.adapter.view.PickerGridAdapter$1.onClick(PickerGridAdapter.java:74)
W/System.err(23374):    at android.view.View.performClick(View.java:7189)
W/System.err(23374):    at android.view.View.performClickInternal(View.java:7166)
W/System.err(23374):    at android.view.View.access$3500(View.java:819)
W/System.err(23374):    at android.view.View$PerformClick.run(View.java:27682)
W/System.err(23374):    at android.os.Handler.handleCallback(Handler.java:883)
W/System.err(23374):    at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err(23374):    at android.os.Looper.loop(Looper.java:224)
W/System.err(23374):    at android.app.ActivityThread.main(ActivityThread.java:7592)
W/System.err(23374):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(23374):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
W/System.err(23374):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by lawmake-praveen** [comment]
There is no good packages for taking pictures and show it inside the app.
Another popular package image_picker is make the app crash for some devices sometimes.
Is there any alternative for taking pictures inside the app?
